# Generated by Django 4.2 on 2024-07-11 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldCrypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin_name", models.CharField(max_length=100)),
                ("amount_sold", models.DecimalField(decimal_places=8, max_digits=20)),
                ("date_sold", models.DateField()),
                ("dentined_currency", models.CharField(max_length=30)),
                (
                    "price_when_sold_real",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "price_when_sold_usdt",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_coins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CryptoInvestments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin_name", models.CharField(max_length=100)),
                ("coin_code", models.CharField(max_length=30)),
                ("amount_bought", models.DecimalField(decimal_places=5, max_digits=20)),
                ("date_invested", models.DateField()),
                (
                    "current_price_usdt",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "price_when_bought_usdt",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "price_when_bought_real",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("original_currency", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
