# Generated by Django 4.2 on 2024-07-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_investments_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="default user", max_length=255),
        ),
    ]
